/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author guilherme
 */
public class FTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FTelaPrincipl
     */
    public FTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadCliente = new javax.swing.JMenuItem();
        miCadAutomovel = new javax.swing.JMenuItem();
        miCadRevisao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miConsRevisao = new javax.swing.JMenuItem();
        miConsCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoMobile");

        jMenu1.setText("Cadastro");

        miCadCliente.setText("Cliente");
        jMenu1.add(miCadCliente);

        miCadAutomovel.setText("Automovel");
        jMenu1.add(miCadAutomovel);

        miCadRevisao.setText("Revisao");
        miCadRevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadRevisaoActionPerformed(evt);
            }
        });
        jMenu1.add(miCadRevisao);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        miConsRevisao.setText("Revisao");
        miConsRevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsRevisaoActionPerformed(evt);
            }
        });
        jMenu2.add(miConsRevisao);

        miConsCliente.setText("Cliente");
        miConsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsClienteActionPerformed(evt);
            }
        });
        jMenu2.add(miConsCliente);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miCadRevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadRevisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadRevisaoActionPerformed

    private void miConsRevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsRevisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miConsRevisaoActionPerformed

    private void miConsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miConsClienteActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem miCadAutomovel;
    public javax.swing.JMenuItem miCadCliente;
    public javax.swing.JMenuItem miCadRevisao;
    public javax.swing.JMenuItem miConsCliente;
    public javax.swing.JMenuItem miConsRevisao;
    // End of variables declaration//GEN-END:variables
}
